# Generated by Django 4.0.2 on 2022-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='brief_intro',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
