# Generated by Django 4.0.2 on 2022-08-08 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_file_content_file_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
