# Generated by Django 4.0.5 on 2022-08-08 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_file_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('file_id', models.IntegerField(verbose_name='文件ID')),
                ('delete_time', models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='文件放入回收站时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('delete_time', models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='项目放入回收站时间')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否已被放入回收站'),
        ),
        migrations.AddField(
            model_name='file',
            name='display',
            field=models.BooleanField(default=False, verbose_name='是否对所有人开放预览'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否已被放入回收站'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='design_num',
            field=models.IntegerField(default=0, verbose_name='项目内原型设计文件个数'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='file_num',
            field=models.IntegerField(default=0, verbose_name='项目内文件个数'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='text_num',
            field=models.IntegerField(default=0, verbose_name='项目内文档文件个数'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='uml_num',
            field=models.IntegerField(default=0, verbose_name='项目内UML文件个数'),
        ),
        migrations.AddField(
            model_name='projectt',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=80, verbose_name='项目更新时间'),
            preserve_default=False,
        ),
    ]
