# Generated by Django 4.0.5 on 2022-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='团队ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='团队名称')),
                ('establisher', models.CharField(max_length=128, verbose_name='创始人用户名')),
                ('establish_time', models.DateTimeField(max_length=80, verbose_name='团队成立时间')),
                ('member_num', models.IntegerField(default=1, verbose_name='成员数')),
                ('project_num', models.IntegerField(default=0, verbose_name='项目数')),
            ],
        ),
    ]
