# Generated by Django 4.0.2 on 2022-08-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_establish_time_team_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='团队成立时间'),
        ),
    ]
