# Generated by Django 4.0.5 on 2022-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_uml'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.CharField(default='https://miaotu-headers.oss-cn-hangzhou.aliyuncs.com/yonghutouxiang/Transparent_Akkarin.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='brief_intro',
            field=models.CharField(default='这个团队很懒，什么也没写', max_length=255),
        ),
    ]
