# Generated by Django 4.0.2 on 2022-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_avatar_team_brief_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='brief_intro',
            field=models.CharField(default='这个团队很懒，什么也没写', max_length=1024),
        ),
    ]
