# Generated by Django 4.0.2 on 2022-08-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_in_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('priority', models.IntegerField(verbose_name='该成员在该项目中权限等级')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('sender', models.CharField(max_length=128, verbose_name='发送/操作者username')),
                ('receiver', models.CharField(max_length=128, verbose_name='接收者username')),
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='消息发送时间')),
                ('message_type', models.IntegerField(verbose_name='信息种类')),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('file_id', models.IntegerField(verbose_name='文件ID')),
                ('username', models.CharField(max_length=128, verbose_name='操作者username')),
                ('send_time', models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='消息发送时间')),
                ('message_type', models.IntegerField(verbose_name='信息种类')),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('sender', models.CharField(max_length=128, verbose_name='发送/操作者username')),
                ('receiver', models.CharField(max_length=128, verbose_name='接收者username')),
                ('send_time', models.DateTimeField(auto_now_add=True, max_length=80, verbose_name='消息发送时间')),
                ('message_type', models.IntegerField(verbose_name='信息种类')),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
