# Generated by Django 4.0.2 on 2022-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_in_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('team_id', models.IntegerField(verbose_name='团队ID')),
                ('priority', models.IntegerField(verbose_name='该成员在该项目中权限等级')),
            ],
        ),
    ]
