# Generated by Django 4.1 on 2022-08-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmessage",
            name="delete_file_name",
            field=models.CharField(max_length=128, null=True, verbose_name="被删除文件名"),
        ),
        migrations.AddField(
            model_name="teammessage",
            name="delete_project_name",
            field=models.CharField(max_length=128, null=True, verbose_name="被删除项目名"),
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="project_id",
            field=models.IntegerField(null=True, verbose_name="项目ID"),
        ),
        migrations.AlterField(
            model_name="projectmessage",
            name="team_id",
            field=models.IntegerField(null=True, verbose_name="团队ID"),
        ),
        migrations.AlterField(
            model_name="teammessage",
            name="project_id",
            field=models.IntegerField(null=True, verbose_name="项目ID"),
        ),
        migrations.AlterField(
            model_name="teammessage",
            name="receiver",
            field=models.CharField(
                max_length=128, null=True, verbose_name="接收者username"
            ),
        ),
    ]
