# Generated by Django 4.0.2 on 2022-08-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_personalmessage_projectmessage_teammessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member_in_team',
            index=models.Index(fields=['username'], name='username_index'),
        ),
    ]
