name: Django_deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull and reload on Aliyun
        run: sshpass -p ${{secrets.ECS_PASSWORD}} ssh -o StrictHostKeyChecking=no couteau69586@${{secrets.ECS_IP}} "cd ~/backend;conda activate django;python kill.py;git pull;git checkout main;python run.py;"