name: Django_deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull and reload on Aliyun
        run: sshpass -p ${{secrets.ECS_PASSWORD}} ssh -o StrictHostKeyChecking=no couteau69586@${{secrets.ECS_IP}} "cd ~/backend; chmod +x ./test.sh; bash ./test.sh"